version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      args:
        SERVICE_NAME: user-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/social

  content-service:
    build:
      context: .
      args:
        SERVICE_NAME: content-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/social

  feed-service:
    build:
      context: .
      args:
        SERVICE_NAME: feed-service
    ports:
      - "8082:8082"
    depends_on:
      - content-service
      - user-service

  api-gateway:
    build:
      context: .
      args:
        SERVICE_NAME: api-gateway
    ports:
      - "8083:8083"
    depends_on:
      - user-service
      - content-service
      - feed-service

volumes:
  postgres_data:
