spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**, /profile/**, /follow/**
        - id: content-service
          uri: http://localhost:8081
          predicates:
            - Path=/content/**, /like/**, /comment/**
        - id: feed-service
          uri: http://localhost:8082
          predicates:
            - Path=/feed/**

# This is a placeholder file. Configuration will be added later.
# Add swagger config
springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: content-service
        url: /content-service/v3/api-docs
      - name: feed-service
        url: /feed-service/v3/api-docs

app:
  jwtSecret: some-secret-key-that-is-long-enough
